# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sun Aug 19 21:56:50 2012 from "/home/nik/document/plants/plants.wxg"

import wx

# begin wxGlade: dependencies
# end wxGlade
from DataBase import DataBase
from DataBase import Plants
# begin wxGlade: extracode

# end wxGlade


class AddDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.labelNumber = wx.StaticText(self, -1, u"编号：")
        self.txtNumber = wx.TextCtrl(self, -1, "")
        self.labelName = wx.StaticText(self, -1, u"客户姓名：")
        self.txtName = wx.TextCtrl(self, -1, "")
        self.labelType = wx.StaticText(self, -1, u"品种：")
        self.txtType = wx.TextCtrl(self, -1, "")
        self.labelPhone = wx.StaticText(self, -1, u"电话：")
        self.txtPhone = wx.TextCtrl(self, -1, "")
        self.labelAddress = wx.StaticText(self, -1, u"地址：")
        self.txtAddress = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelInfo = wx.StaticText(self, -1, u"寄养时状况：")
        self.txtInfo = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.btnOK = wx.Button(self, -1, u"保存")
        self.btnCancel = wx.Button(self, -1, u"取消")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onSave, self.btnOK)
        self.Bind(wx.EVT_BUTTON, self.onCancel, self.btnCancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AddDialog.__set_properties
        self.SetTitle(u"添加新寄养")
        self.txtAddress.SetMinSize((300,50))
        self.txtInfo.SetMinSize((300,50))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddDialog.__do_layout
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        self.buttonSizer = buttonSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.formSizer = formSizer = wx.BoxSizer(wx.VERTICAL)
        formSizer.Add(self.labelNumber, 0, wx.TOP, 20)
        formSizer.Add(self.txtNumber, 0, wx.TOP | wx.EXPAND, 5)
        formSizer.Add(self.labelName, 0, wx.TOP | wx.BOTTOM, 5)
        formSizer.Add(self.txtName, 0, wx.EXPAND, 0)
        formSizer.Add(self.labelType, 0, wx.TOP | wx.BOTTOM, 5)
        formSizer.Add(self.txtType, 0, wx.EXPAND, 0)
        formSizer.Add(self.labelPhone, 0, wx.TOP | wx.BOTTOM, 5)
        formSizer.Add(self.txtPhone, 0, wx.EXPAND, 0)
        formSizer.Add(self.labelAddress, 0, wx.TOP | wx.BOTTOM, 5)
        formSizer.Add(self.txtAddress, 0, wx.EXPAND, 0)
        formSizer.Add(self.labelInfo, 0, wx.TOP | wx.BOTTOM, 5)
        formSizer.Add(self.txtInfo, 0, wx.BOTTOM | wx.EXPAND, 20)
        mainSizer.Add(formSizer, 0, wx.LEFT | wx.RIGHT | wx.EXPAND, 20)
        buttonSizer.Add(self.btnOK, 0, wx.LEFT | wx.RIGHT, 5)
        buttonSizer.Add(self.btnCancel, 0, wx.LEFT | wx.RIGHT | wx.EXPAND, 5)
        mainSizer.Add(buttonSizer, 0, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 20)
        self.SetSizer(mainSizer)
        mainSizer.Fit(self)
        self.Layout()
        # end wxGlade

    def onSave(self, event):
        dataBase = DataBase()
        plants = Plants.getByDialog(self)
        dataBase.addNew(plants)
        self.Close()
        self.GetParent().loadData()
        
    def onCancel(self, event):
        self.Close()

# end of class AddDialog
