# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sun Aug 19 21:56:50 2012 from "/home/nik/document/plants/plants.wxg"

import wx

# begin wxGlade: dependencies
import sys
# end wxGlade

# begin wxGlade: extracode
from AddDialog import AddDialog
from DataBase import DataBase
from MainGrid import MainGrid
# end wxGlade

reload(sys)
sys.setdefaultencoding('utf-8')


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)

        # Menu Bar
        self.mainMenuBar = wx.MenuBar()
        self.menuFile = wx.Menu()
        self.menuNew = wx.MenuItem(self.menuFile, wx.NewId(), u"新寄养(&N)", u"新寄养", wx.ITEM_NORMAL)
        self.menuFile.AppendItem(self.menuNew)
        self.menuFile.AppendSeparator()
        self.menuExit = wx.MenuItem(self.menuFile, wx.NewId(), u"退出(&X)", u"退出", wx.ITEM_NORMAL)
        self.menuFile.AppendItem(self.menuExit)
        self.mainMenuBar.Append(self.menuFile, u"文件(&F)")
        self.menuHelp = wx.Menu()
        self.menuAbout = wx.MenuItem(self.menuHelp, wx.NewId(), u"关于(&A)", u"关于", wx.ITEM_NORMAL)
        self.menuHelp.AppendItem(self.menuAbout)
        self.mainMenuBar.Append(self.menuHelp, u"帮助(&H)")
        self.SetMenuBar(self.mainMenuBar)
        # Menu Bar end
        self.mainStatusBar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.mainGrid = MainGrid(self)
        self.labelSearch = wx.StaticText(self, -1, u"电话号码搜索：")
        self.txtSearch = wx.TextCtrl(self, -1, "")
        self.btnSearch = wx.Button(self, -1, u"搜索(&S)")
        self.labelPage = wx.StaticText(self, -1, u"共9页 当前第2页")
        self.btnPrev = wx.Button(self, -1, u"上一页")
        self.btnNext = wx.Button(self, -1, u"下一页")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.onAddNew, self.menuNew)

        self.loadData()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(u"花木寄养管理系统")
        self.mainStatusBar.SetStatusWidths([-1])
        # statusbar fields
        mainStatusBar_fields = [u"花木寄养管理系统"]
        for i in range(len(mainStatusBar_fields)):
            self.mainStatusBar.SetStatusText(mainStatusBar_fields[i], i)

        #self.mainGrid.AutoSizeColumns(False)
        self.mainGrid.CreateGrid(40, 7)
        self.mainGrid.EnableEditing(0)
        self.mainGrid.EnableDragRowSize(0)
        self.mainGrid.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
        self.mainGrid.SetColLabelValue(0, u"编号")
        self.mainGrid.SetColLabelValue(1, u"姓名")
        self.mainGrid.SetColLabelValue(2, u"地址")
        self.mainGrid.SetColLabelValue(3, u"电话")
        self.mainGrid.SetColLabelValue(4, u"寄养日期")
        self.mainGrid.SetColLabelValue(5, u"花木品种")
        self.mainGrid.SetColLabelValue(6, u"寄养时状况")
        self.mainGrid.SetMinSize((800, 300))
        self.mainGrid.setColWidthProportions([0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.2])
        self.mainGrid.SetCellHighlightPenWidth(0)
        self.mainGrid.SetRowLabelSize(30)
        self.txtSearch.SetMinSize((200, -1))
        self.btnSearch.SetMinSize((60, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        controlSizer = wx.BoxSizer(wx.HORIZONTAL)
        mainSizer.Add(self.mainGrid, 1, wx.EXPAND, 2)
        controlSizer.Add(self.labelSearch, 0, wx.ALL, 5)
        controlSizer.Add(self.txtSearch, 1, wx.LEFT, 5)
        controlSizer.Add(self.btnSearch, 0, wx.LEFT, 5)
        controlSizer.Add((0, 0), 1, wx.EXPAND, 0)
        controlSizer.Add(self.labelPage, 0, wx.ALL, 5)
        controlSizer.Add(self.btnPrev, 0, 0, 0)
        controlSizer.Add(self.btnNext, 0, wx.LEFT | wx.RIGHT, 5)
        mainSizer.Add(controlSizer, 0, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(mainSizer)
        mainSizer.Fit(self)
        self.Layout()
        mainSize = self.GetSize()
        self.SetMinSize(mainSize)
        self.mainGrid.fixWidth()
        # end wxGlade

    def loadData(self):
        self.mainGrid.ClearGrid()
        dataBase = DataBase()
        cur = dataBase.fetch()
        data = cur.fetchall()
        row = 0
        cell = -1
        for item in data:
            for value in item:
                if cell == -1:
                    cell = cell + 1
                    self.mainGrid.setRowAttachmentData(row, value)
                    continue
                self.mainGrid.SetCellValue(row, cell, "%s" % value)
                cell = cell + 1
            cell = -1
            row = row + 1
        row = 0
        self.mainGrid.Refresh()

    def onAddNew(self, event):  # wxGlade: MainFrame.<event_handler>
        addDialog = AddDialog(self)
        addDialog.ShowModal()
        addDialog.Destroy()


# end of class MainFrame
