#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sun Aug 19 21:56:50 2012 from "/home/nik/document/plants/plants.wxg"

import wx
from MainFrame import MainFrame


class mainApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        mainFrame = MainFrame(None, -1, "")
        self.SetTopWindow(mainFrame)
        mainFrame.Show()
        return 1

# end of class mainApp

if __name__ == "__main__":
    main = mainApp(0)
    main.MainLoop()
